services:
  db:
    image: postgres:16.3
    restart: always
    networks:
      metanet1:
        ipv4_address: 173.0.0.10
    cpus: 2.0
    mem_limit: 4G
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=${METABASE_POSTGRES_DB}
      - POSTGRES_USER=${METABASE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${METABASE_POSTGRES_PASSWORD}
      - TZ=Europe/Paris
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=2GB"
      - "-c"
      - "effective_cache_size=6GB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "checkpoint_completion_target=0.7"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=100"
      - "-c"
      - "random_page_cost=4"
      - "-c"
      - "effective_io_concurrency=2"
      - "-c"
      - "work_mem=5242kB"
      - "-c"
      - "min_wal_size=1GB"
      - "-c"
      - "max_wal_size=4GB"
      - "-c"
      - "max_worker_processes=4"
      - "-c"
      - "max_parallel_workers_per_gather=2"
      - "-c"
      - "max_parallel_workers=4"

  metabase:
    image: metabase/metabase:latest
    restart: always
    container_name: metabase
    hostname: metabase
    ports:
      - "${METABASE_PORT}:3000"
    environment:
      MB_DB_PORT: 5432
      MB_DB_HOST: postgres
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: "${METABASE_POSTGRES_DB}"
      MB_DB_USER: "${METABASE_POSTGRES_USER}"
      MB_DB_PASS: "${METABASE_POSTGRES_PASSWORD}"
    networks:
      metanet1:
        ipv4_address: 173.0.0.30
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_DB=${METABASE_POSTGRES_DB}
      - POSTGRES_USER=${METABASE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${METABASE_POSTGRES_PASSWORD}
      - TZ=Europe/Paris
    networks:
      metanet1:
        ipv4_address: 173.0.0.50

networks:
  metanet1:
    driver: bridge
    ipam:
      config:
        - subnet: 173.0.0.0/16
